name: prayer_schedule
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  geolocator: ^5.2.1
  equatable: ^1.0.3
  flutter_bloc: ^3.2.0
  flutter_cupertino_date_picker: ^1.0.12
  flutter_screenutil: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true